// OP_CODEGEN(name, n_operands, value, priority, text)

OP_CODEGEN(B,             2, (arg1 <  arg2),     1, "les")
OP_CODEGEN(BE,            2, (arg1 <= arg2),     1, "leq")
OP_CODEGEN(A,             2, (arg1 >  arg2),     1, "gre")
OP_CODEGEN(AE,            2, (arg1 >= arg2),     1, "geq")
OP_CODEGEN(E,             2, (arg1 == arg2),     1, "eq")
OP_CODEGEN(NE,            2, (arg1 != arg2),     1, "neq")
   
OP_CODEGEN(ADD,           2, (arg1 + arg2),      2, "+")
OP_CODEGEN(SUB,           2, (arg1 - arg2),      2, "-")
OP_CODEGEN(MUL,           2, (arg1 * arg2),      3, "*")
OP_CODEGEN(DIV,           2, (arg1 / arg2),      3, "/")
OP_CODEGEN(POW,           2, intPow(arg1, arg2), 4, "^")

OP_CODEGEN(ASSIGN,        2, 0,                  0, "=")
OP_CODEGEN(IF,            2, 0,                  0, "if")
OP_CODEGEN(ELSE,          1, 0,                  0, "else")
OP_CODEGEN(WHILE,         2, 0,                  0, "while")
OP_CODEGEN(RET,           1, 0,                  0, "return")
OP_CODEGEN(FUNC,          3, 0,                  0, "func")
OP_CODEGEN(VAR,           1, 0,                  0, "var")
OP_CODEGEN(COMMA,         2, 0,                  0, ",")
      
OP_CODEGEN(OPEN_BRACKET,  0, 0,                  0, "(")
OP_CODEGEN(CLOSE_BRACKET, 0, 0,                  0, ")")
OP_CODEGEN(END,           0, 0,                  0, "$")
